"use client";
import BlogCard from "@/components/blog-card";
import { useAllBlogs } from "@/hooks/get-all-blogs";
import React from "react";

// Generated by https://quicktype.io

// Generated by https://quicktype.io

export interface IBlog {
  id: string;
  createdAt: string;
  updatedAt: string;
  published: boolean;
  title: string;
  content: Content;
}

export interface Content {
  time: number;
  blocks: Block[];
  version: string;
}

export interface Block {
  id: string;
  type: string;
  data: Data;
}

export interface Data {
  text?: string;
  style?: string;
  items?: string[];
}

function BlogsPage() {
  const { data: blogs, isLoading } = useAllBlogs();
  return (
    <div className="container">
      <div className="grid grid-cols-3 gap-5 mt-[5vh]">
        {blogs?.map((blog: IBlog, id: any) => (
          <BlogCard key={id} blog={blog} />
        ))}
      </div>
    </div>
  );
}

export default BlogsPage;
